[General]
# Debug | Release
ENV = "Release"
JWTTOKEN = "wksm4ch03hhsdr9p91gjwipc4gpn6ith"

[Mysql]
IsInit = true
DSN = "root:123456@tcp(192.168.56.200:3308)/goboot?loc=Local&charset=utf8&parseTime=true"
MaxOpenConn = 20
MaxIdleConn = 20

[Redis]
IsInit = false
Addr = "192.168.56.200:6379"
Password = ""
DB = 0
PoolSize = 10
